name: Update Checksum

on:
  push:
    branches:
      - main

jobs:
  checksum:
    if: "!contains(github.event.head_commit.message, '[checksum]')"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Calculate checksum
        run: |
          CHECKSUM=$(
            {
              find models notebooks -type f -print0 | xargs -0 sha256sum
              sha256sum verify.sh requirements.txt
            } | sha256sum | awk '{print $1}'
          )

          mkdir -p checksum
          echo "$CHECKSUM" > checksum/project.sha256

      - name: Commit checksum
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add checksum/project.sha256

          git diff --cached --quiet || \
            git commit -m "Update checksum [checksum]"

          git push