name: "hello this is yml"

on: 
  push:
    branches: main
  
  pull_request:
    branches: main
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Hii this is supposed to work"
        uses: actions/checkout@v4  
        
      - name: "setup nodejs"
        uses: "actions/setup-node@v4"
        with:
          node-version: "22"
        
      - name: "install dependencies"  
        run: npm ci
      
      - name: "install golang"
        uses: actions/setup-go@v5

      - name: "display version"
        run: go version
      
      - name: "install pm2"
        run: npm install -g pm2
    
      - name: "run node server"
        run: pm2 start main.js 
      
      - name: "get request from go client"
        run: go run main.go